name: Deploy to Hosted Service

on:
    push:
        tags:
            - "*"

jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install Yarn
              run: npm i -g yarn
            - name: Install Libs
              run: yarn --frozen-lockfile
            - name: Codegen
              run: yarn codegen
            - name: Build
              run: yarn build
            - name: Deploy to TheGraph Hosted Service
              run: |
                  npx graph deploy --access-token ${{secrets.GRAPH_ACCESS_TOKEN}} aavegotchi/gotchiverse-matic subgraph.yaml --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/
              shell: bash
